### ISSUE TITLE
jupyter chart uses deprecated ingress apiVersion

### ISSUE THREAD

**Issue by tarioch** [Gradiant/bigdata-charts#50]
Since Kubernetes 1.19 the extensions/v1beta1 for ingress has been deprecated and with the recently released 1.22 they got dropped. Would be good to upgrade this to networking.k8s.io/v1 see https://kubernetes.io/docs/reference/using-api/deprecation-guide/

**Comment by cgiraldo** [comment]
We have made a major refactoring of jupyter helm chart. Now we levearage bitnami common library to manage several portions of the templates, such as the ingress apiVersion. networking.k8s.io/v1 should be now available.

We have also rename the repository from charts to bigdata-charts.
