### ISSUE TITLE
jupyter-0.1.7 chart only mounts /home/jovyan/git-notebooks.sh

### ISSUE THREAD

**Issue by tarioch** [Gradiant/bigdata-charts#53]
I'm not sure if this is intentional. I'm not using gitNotebooks and my pv for /home/jovyan has several things included (e.g. some special ssh keys I need). Now even with gitNotebooks disabled, it only mounts the subpath git-notebooks.sh so all my other things from the pv are not in there anymore.

**Comment by tarioch** [comment]
Did a quick test, if I manually drop the 

```yaml
subPath: "git-notebooks.sh"
```

from the statefulset

everything works as before.

**Comment by cgiraldo** [comment]
Thanks for reporting.
 That is not intentional but a typo in the statefulset declaration.
I hope the bug didn't lead to any loose of data for you.
jupter-0.1.8 should now get this fix.

**Comment by cgiraldo** [comment]
Thanks for reporting.
 That is not intentional but a typo in the statefulset declaration.
I hope the bug didn't lead to any loose of data for you.
jupter-0.1.8 should now get this fix.

**Comment by tarioch** [comment]
nothing lost, works perfectly, thank you very much
