### ISSUE TITLE
[chart/jupyter] Need update target repo in artifacthub

### ISSUE THREAD

**Issue by ymrsmns** [Gradiant/bigdata-charts#55]
Hi

Please update information in artifacthub, 
not view new version 
last rename repository
https://artifacthub.io/packages/helm/gradiant/jupyter

**Comment by cgiraldo** [comment]
We can't remove previous repository because we can't claim its ownership right now.

But we have publish the new repository. Find it here:

https://artifacthub.io/packages/helm/gradiant-bigdata/jupyter

**Comment by ymrsmns** [comment]
thank you very much for the information
