### ISSUE TITLE
Helm Chart URL broken

### ISSUE THREAD

**Issue by mdiianni** [Gradiant/bigdata-charts#63]
Hello, the helm chart URL is broken https://gradiant.github.io/charts/ is this something you can look into or could you please confirm if the chart has been moved somewhere else and where? Thank you and regards.

**Comment by cgiraldo** [comment]
Yes. Check the README.md of the repo. the repository is now on:
```
helm repo add bigdata-gradiant https://gradiant.github.io/bigdata-charts/
```

Can you tell us where did you find the old url? we have modify several references but maybe there are some places with the old url.

Regards
